import os
from collections import OrderedDict

STICKER_YOBA = 'CAACAgIAAxkBAAIMAl7cmE5fihYAATVzP_zYoQsElM_SngACFgIAArGOvwJa8QcMTEIJbRoE'
STICKER_FRY_FUCK_YOU = 'CAACAgIAAxkBAAILqV7WXIYpcS64zxf8JLJxPXjuVVdVAALDAQACPQ3oBHBpwFiKM26AGgQ'
STICKER_ANIME_CHAN_KONNICHIWA = 'CAACAgIAAxkBAAIMAAFe3Jcb61VTJ1ujuWBZyJsrBRB8swACVwEAAhAabSKlKzxU-3o0qhoE'

EMOJI_ANGRY = u'\U0001F620'
EMOJI_SCARED = u'\U0001F631'
EMOJI_VERY_ANGRY = u'\U0001F621'
EMOJI_SUNGLASSES = u'\U0001F60E'
EMOJI_MAN_SHRUGGING = u'\U0001F937'

USERNAME_FAL = 'faleksander'
USERNAME_OLYA = 'olga_gr'
USERNAME_VOVA = 'dadyavova'
USERNAME_ILUHA = 'ikuzmin'
USERNAME_JENIA = 'jbukhtiyarova'
USERNAME_KSUHA = 'kvetrova'
USERNAME_SANIA = 'aminakov'
USERNAME_SLAVA = 'koshekans'
USERNAME_ANDREJ = 'enqcore'
USERNAME_YANA_SHPAK = 'yanaevs'
USERNAME_YANA_4RINA = 'ychetirina'
USERNAME_KALICHKIN = 'akalichkin'
USERNAME_MISHA = 'mlegchenko'

BET_USERNAME_DICT = OrderedDict()
BET_USERNAME_DICT[USERNAME_SANIA] = 'БИГ БОСС'
BET_USERNAME_DICT[USERNAME_FAL] = '4fal'
BET_USERNAME_DICT[USERNAME_OLYA] = 'Оля'
BET_USERNAME_DICT[USERNAME_VOVA] = 'Вова'
BET_USERNAME_DICT[USERNAME_ILUHA] = 'Илюха'
BET_USERNAME_DICT[USERNAME_JENIA] = 'Женя'
BET_USERNAME_DICT[USERNAME_KSUHA] = 'Ксюха'
BET_USERNAME_DICT[USERNAME_SLAVA] = 'Слава'
BET_USERNAME_DICT[USERNAME_ANDREJ] = 'Адрюха'
BET_USERNAME_DICT[USERNAME_YANA_SHPAK] = 'Яна Шпак'
BET_USERNAME_DICT[USERNAME_YANA_4RINA] = 'Яна 4на'
BET_USERNAME_DICT[USERNAME_KALICHKIN] = 'АРТЁМ'
BET_USERNAME_DICT[USERNAME_MISHA] = 'МИША'

KEY_TO_POS = {k: pos for pos, k in enumerate(BET_USERNAME_DICT)}

PROJECT_ID = os.environ['GCP_PROJECT']
ENTRY_POINT = os.environ['ENTRY_POINT']
FUNCTION_REGION = os.environ['FUNCTION_REGION']
URL = f'https://{FUNCTION_REGION}-{PROJECT_ID}.cloudfunctions.net/{ENTRY_POINT}'

TELEGRAM_TOKEN = os.environ['TELEGRAM_TOKEN']
