import os

FRY_FUCK_YOU_STICKER = 'CAACAgIAAxkBAAILqV7WXIYpcS64zxf8JLJxPXjuVVdVAALDAQACPQ3oBHBpwFiKM26AGgQ'

EMOJI_ANGRY = u'\U0001F620'
EMOJI_SCARED = u'\U0001F631'

PROJECT_ID = os.environ['GCP_PROJECT']
ENTRY_POINT = os.environ['ENTRY_POINT']
FUNCTION_REGION = os.environ['FUNCTION_REGION']
URL = f'https://{FUNCTION_REGION}-{PROJECT_ID}.cloudfunctions.net/{ENTRY_POINT}'

TOKEN = os.environ['TOKEN']
